from __future__ import annotations

from collections.abc import Generator
from typing import Any

from anthropic import Anthropic

from codebase_qa.embeddings import embed
from codebase_qa.vectorstore import query

MODEL = "claude-sonnet-4-6"

SYSTEM = (
    "You are a code assistant. Answer questions using ONLY the provided source "
    "code excerpts. For every claim, cite the file and line range in the format "
    "`path/to/file.py:10-25`. If the context does not contain enough information "
    "to answer confidently, say so rather than guessing."
)

_MOCK_ANSWER = (
    "[MOCK] Pipeline OK — retrieval worked, Claude API call skipped.\n"
    "[MOCK] In production this answer would be generated by {model}."
).format(model=MODEL)

# Event types yielded by iter_answer:
#   {"type": "text",    "content": str}       — a chunk of answer text
#   {"type": "sources", "content": list[dict]} — source metadata (final event)


def _retrieve(
    question: str,
    collection_name: str,
    top_k: int,
) -> tuple[list[dict], str]:
    """Embed question and return (chunks, formatted context string)."""
    [q_vec] = embed([question])
    chunks = query(collection_name, q_vec, top_k=top_k)
    if not chunks:
        return [], ""
    context = "\n\n".join(
        f"# {c['metadata']['file']}:{c['metadata']['start_line']}-{c['metadata']['end_line']}\n{c['text']}"
        for c in chunks
    )
    return chunks, context


def iter_answer(
    question: str,
    collection_name: str = "codebase",
    top_k: int = 5,
    *,
    mock: bool = False,
) -> Generator[dict[str, Any], None, None]:
    """Yield answer events for a question against an indexed collection.

    Yields dicts with ``type`` equal to ``"text"`` (answer chunks) or
    ``"sources"`` (final metadata list). Callers consume this generator;
    the CLI prints text to stdout, the API serialises events as SSE.
    """
    chunks, context = _retrieve(question, collection_name, top_k)

    if not chunks:
        yield {"type": "text", "content": "No indexed chunks found. Run `codebase-qa index <path>` first."}
        return

    sources = [c["metadata"] for c in chunks]

    if mock:
        yield {"type": "text", "content": _MOCK_ANSWER}
        yield {"type": "sources", "content": sources}
        return

    client = Anthropic()
    with client.messages.stream(
        model=MODEL,
        max_tokens=4096,
        thinking={"type": "adaptive"},
        system=SYSTEM,
        messages=[
            {
                "role": "user",
                "content": f"<context>\n{context}\n</context>\n\n{question}",
            }
        ],
    ) as stream:
        for text in stream.text_stream:
            yield {"type": "text", "content": text}

    yield {"type": "sources", "content": sources}


def answer(
    question: str,
    collection_name: str = "codebase",
    top_k: int = 5,
    *,
    mock: bool = False,
) -> list[dict]:
    """CLI entry point: stream answer text to stdout, return source metadata list."""
    sources: list[dict] = []
    got_sources = False

    for event in iter_answer(question, collection_name, top_k, mock=mock):
        if event["type"] == "text":
            print(event["content"], end="", flush=True)
        elif event["type"] == "sources":
            print()
            got_sources = True
            sources = event["content"]

    if not got_sources:
        print()  # trailing newline for error messages

    return sources


def answer_sync(
    question: str,
    collection_name: str = "codebase",
    top_k: int = 5,
    *,
    mock: bool = False,
) -> tuple[str, list[dict]]:
    """Non-streaming variant: collect full answer text, return (text, sources)."""
    text_parts: list[str] = []
    sources: list[dict] = []

    for event in iter_answer(question, collection_name, top_k, mock=mock):
        if event["type"] == "text":
            text_parts.append(event["content"])
        elif event["type"] == "sources":
            sources = event["content"]

    return "".join(text_parts), sources
